import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import SideBar from '@/components/SideBar'

import { Session } from 'next-auth'
import { SessionProvider } from '@/components/SessionProvider'
import { getServerSession } from 'next-auth'
import { authOptions } from './api/[...nextauth]'
import Login from '@/components/Login'
// import { SessionProvider } from 'next-auth/react'

const inter = Inter({ subsets: ['latin'] })

// type Props = {
//   children: React.ReactNode
//   session: Session | null
// }

export const metadata: Metadata = {
  title: 'ChatGPT messenger',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const session = await getServerSession(authOptions)

  return (
    <html lang="en">
      <head />
      <body className={inter.className}>
        <SessionProvider session={session}>
          {!session ? (
            <Login />
          ) : (
            <div className="flex">
              <div className="bg-[#202123] max-w-xs h-screen overflow-y-auto md:min-w-[18rem]">
                <SideBar />
              </div>

              {/* ClientProvider - Notification */}

              <div className="bg-[#343541] flex-1">{children}</div>
            </div>
          )}
        </SessionProvider>
      </body>
    </html>
  )
}
